SELECT B.CATEGORY, SUM(S.SALES) TOTAL_SALES
FROM BOOK B
JOIN (SELECT * FROM BOOK_SALES
     WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01') AS S
     ON B.BOOK_ID = S.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY